ACME/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('modules.home.urls')),
    path('clientes', include('modules.clientes.urls')),
    # path('accounts/', include('users.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

modules/clientes/urls.py
from django.contrib import admin
from django.conf.urls import url
from django.urls import path
from django.urls.conf import include
from . import views

app_name = 'clientes'

urlpatterns = [
    path('add-client/',
         views.AddClient.as_view(), name='add-client'),
    path('add-filial/',
         views.AddFilial.as_view(), name='add-filial'),
    path('list-filial/',
         views.ListFilial.as_view(), name='list-filial'),
    path('update-filial/', views.UpdateFilial.as_view(), name='update-filial')
]

modules/home/urls.py
from django.contrib import admin
from django.conf.urls import url
from django.urls import path
from django.urls.conf import include
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.Home.as_view(), name='index'),
    path('add-client', views.CreateClient.as_view(), name='add-client'),
    path('update-client/<int:pk>/', views.UpdateClient.as_view(), name='update-client'),
    path('delete/<int:pk>/', views.DeleteClient.as_view(), name='delete-client')
]

modules/home/models.py
from django.db import models
from tools.general.models import SuperClass

modules/home/views.py
from multiprocessing import context
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import View
from django.views.generic.base import TemplateView
from django.views.generic.detail import DetailView
from ..clientes.models import Clients
from django.views.generic.list import ListView
from django.views.generic import TemplateView, ListView, DetailView, View, RedirectView, FormView
from ..clientes.forms import FormClient, NewFilial
from django.views.generic.edit import UpdateView, FormView, CreateView, DeleteView

class Home(ListView):
    template_name = "home.html"
    model = Clients
    paginate_by = 7

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = FormClient()

        return context

class CreateClient(CreateView):
    model = Clients
    template_name = 'home.html'
    form_class = FormClient
    success_url = reverse_lazy('home:index')

    def get_context_data(self, **kwargs):
        return super().get_context_data(**kwargs)

class UpdateClient(UpdateView):
    model = Clients
    template_name = 'clients.html'
    form_class = FormClient
    success_url = reverse_lazy('home:index')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['newfilial'] = NewFilial(initial={'company': self.kwargs['pk']})
        context['company_pk'] = self.kwargs['pk']
        return context

class DeleteClient(DeleteView):
    model = Clients
    template_name = 'delete.html'
    success_url = reverse_lazy('home:index')

modules/home/templates/delete.html
{% extends "base.html" %}

{% load static %}


  {% block content %}
    <div class="row mt-4 mb-4 ">

        <div class="col-md-10 offset-1 d-block justify-content-center">
        <div class="row m-5">
                <div class="col-md-12 border shadow m-5 p-5">
                    <h3 class="text-center">Deseja apagar a empresa "{{ object.company_name }}" ?</h3>
                    <form method="post" action="">
                        {% csrf_token %}
                        <br>
                        <div class="row">
                            <div class="col-4 offset-2">
                                <a class="btn btn-danger mr-2" href="{% url 'home:index' %}">
                                    Cancelar
                                </a>
                            </div>
                            <div class="col-4 d-flex justify-content-end">
                                <button type="submit" value="" class="btn btn-primary justify-content-end" >
                                    Apagar
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
  {% endblock content %}

  {% block extra_js %}

  {% endblock extra_js %}

modules/home/templates/home.html
{% extends "base.html" %}

{% load static %}

  {% block content %}

  <div class="container">
    {% include 'includes/new-company.html' %}
      <div class="row mt-5 mb-3">
          <div class="col-12 d-flex justify-content-end">
            <button class="btn btn-primary btn-lg btn-newcompany" type="button">
                Novo
            </button>
          </div>
      </div>
      <div class="row">
          <div class="col-12 rounded shadow ">
              <div class="container" id="companys">
                {% for client in object_list %}
                    <div class="row border-bottom pt-3">
                        <div class="col-9">
                            <p class="p-0">{{client.company_name}}</p>
                        </div>
                        <div class="col-1">
                            <div class="text-center text-light rounded-pill {% if client.active == True %} bg-success {% else %} bg-secondary {% endif %}">
                                {% if client.active == True %}
                                    Ativo
                                {% else %}
                                    Inativo
                                {% endif %}
                            </div>
                        </div>
                        <div class="col-2 d-flex justify-content-end pb-2">
                            <a href='{% url "home:update-client" pk=client.id %}' type="button" class="btn btn-round-blue"><img src="{% static 'front/images/edit.svg' %}" width="24px" height="24px"/>Editar</a>
                        </div>
                    </div>
                {% endfor %}
              </div>

          </div>
      </div>
      {% if is_paginated %}
        <div class="row pt-5">
            <div class="col-12 d-flex justify-content-center">
                <ul class="pagination justify-content-end">
                    {% if page_obj.has_previous %}
                        <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">Anterior</a></li>
                    {% else %}
                        <li class="page-item disabled"><span class="page-link">Anterior</span></li>
                    {% endif %}
                    {% for i in paginator.page_range %}
                        {% if page_obj.number == i %}
                            <li class="page-item active"><span class="page-link">{{ i }}</span></li>
                        {% else %}
                            <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
                        {% endif %}
                    {% endfor %}
                    {% if page_obj.has_next %}
                        <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">Proxima</a></li>
                    {% else %}
                        <li class="page-item disabled"><span class="page-link">Proxima</span></li>
                    {% endif %}
                </ul>
            </div>
        </div>
        {% endif %}

  </div>
  {% endblock content %}

  {% block extra_js %}
  <script>
    $('.btn-newcompany').click(function(e){
        e.preventDefault();
        $('#modal-newcompany').modal('show');
    });
  </script>


  <script>
        function ListClients(dados) {
            $.each(dados, function( data ) {
                $("#companys").append(`
                    <div class="row border-bottom pt-3">
                        <div class="col-9">
                            <p class="p-0">${data['company']}</p>
                        </div>
                        <div class="col-1">
                            <div class="text-center text-light rounded-pill bg-success">
                                ${data['active']}
                            </div>
                        </div>
                        <div class="col-2 d-flex justify-content-end pb-2">
                            <button type="button" class="btn btn-round-blue"><img src="{% static 'front/images/edit.svg' %}" width="24px" height="24px"/>Editar</button>
                        </div>
                    </div>
                `);
            });

        }

      $('.btn-sendnewclient').click(function() {
        $.ajax({
            url: '{% url "clientes:add-client" %}',
            data: {
                'company': $('#company').val(),
                'active': $('#active').val(),
            },
            dataType: 'json',
            success: function (data) {
                ListClients(formdata);
            }
        })

      })

  </script>
  {% endblock extra_js %}