ACME/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('modules.home.urls')),
    path('clientes', include('modules.clientes.urls')),
    # path('accounts/', include('users.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

modules/clientes/urls.py
from django.contrib import admin
from django.conf.urls import url
from django.urls import path
from django.urls.conf import include
from . import views

app_name = 'clientes'

urlpatterns = [
    path('add-client/',
         views.AddClient.as_view(), name='add-client'),
    path('add-filial/',
         views.AddFilial.as_view(), name='add-filial'),
    path('list-filial/',
         views.ListFilial.as_view(), name='list-filial'),
    path('update-filial/', views.UpdateFilial.as_view(), name='update-filial')
]

modules/home/urls.py
from django.contrib import admin
from django.conf.urls import url
from django.urls import path
from django.urls.conf import include
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.Home.as_view(), name='index'),
    path('add-client', views.CreateClient.as_view(), name='add-client'),
    path('update-client/<int:pk>/', views.UpdateClient.as_view(), name='update-client'),
    path('delete/<int:pk>/', views.DeleteClient.as_view(), name='delete-client')
]

modules/clientes/models.py
from django.db import models
from tools.general.models import SuperClass
from django.utils.translation import ugettext_lazy as _


class Clients(SuperClass):

    company_name = models.CharField(
        _('Empresa'), 
        blank=False, null=False, max_length=50)


    #created_by = models.ForeignKey(
    #    'users.User', verbose_name=_('criado por'),
    #    on_delete=models.DO_NOTHING, related_name='created_by', blank=False, null=True)


class Filial(SuperClass):

    company = models.ForeignKey(
        Clients, verbose_name='Empresa',
        on_delete=models.CASCADE, blank=False, null=False
    )

    filial_name = models.CharField(
        _('Empresa'), 
        blank=False, null=False, max_length=50)

    cnpj = models.CharField(_('CNPJ'), max_length=18)

modules/clientes/forms.py
from multiprocessing.connection import Client
from django import forms
from django.utils.translation import ugettext_lazy as _
from .models import Clients, Filial

class EditCNPJ(forms.Form):
    TYPE_CHOICES = (
        ('ACTIVE', "Ativo"),
        ('INATIVE', "Inativo")
    )

    active = forms.ChoiceField(
        required=False, label=_('choices'),
        widget=forms.Select(attrs={'class': 'form-control'}),
        choices=TYPE_CHOICES)
    cnpj = forms.CharField(
        label="CNPJ", required=True, widget=forms.TextInput(attrs={'class': 'form-control cnpj-mask', }))
    company_name = forms.CharField(
        label="Nome", required=True, widget=forms.TextInput(attrs={'class': 'form-control', }))

class FormClient(forms.ModelForm):

    TYPE_CHOICES = (
        (True, "Sim"),
        (False, "Não")
    )

    active = forms.ChoiceField(
        required=False, label=_('Ativo'),
        widget=forms.Select(attrs={'class': 'form-control'}),
        choices=TYPE_CHOICES)

    company_name = forms.CharField(
        label="Nome", required=True, widget=forms.TextInput(attrs={'class': 'form-control', 'required': 'True'}))

    class Meta:
        model = Clients
        fields = ['active', 'company_name']

    

class NewFilial(forms.ModelForm):
    TYPE_CHOICES = (
        (True, "Sim"),
        (False, "Não")
    )

    company = forms.ModelChoiceField(
        label='',queryset=Clients.objects.all(), widget=forms.HiddenInput
    )

    active = forms.ChoiceField(
        required=False, label="Ativo",
        widget=forms.Select(attrs={'class': 'form-control'}),
        choices=TYPE_CHOICES)

    cnpj = forms.CharField(
        label="CNPJ", required=True, widget=forms.TextInput(attrs={'class': 'form-control cnpj-mask', }))

    filial_name = forms.CharField(
        label="Nome", required=False, widget=forms.TextInput(attrs={'class': 'form-control', 'required': 'True'}))
    
    class Meta:
        model = Filial
        fields = ['active', 'cnpj', 'filial_name', 'company']

modules/clientes/views.py
from multiprocessing import context
from django.shortcuts import get_object_or_404, render
from django.urls import reverse_lazy
from django.views import View
from django.views.generic.list import ListView
from django.views.generic.base import TemplateView
from django.views.generic.detail import DetailView
from ..clientes.models import Clients, Filial
from django.views.generic.edit import UpdateView, FormView, CreateView
from django.db.models import Q
from .forms import FormClient, NewFilial
from django.http import JsonResponse


class ListClients(FormView):
    template_name = "clients.html"
    form_class = FormClient


class AddClient(View):
    def  get(self, request):
        company_name1 = request.GET.get('company_name', None)
        active1 = request.GET.get('active', None)

        obj = Clients.objects.create(
            active = active1,
            company_name = company_name1,
        )
        
        context = Clients.objects.values()

        print(context)

        data = {
            'context': context
        }
        return JsonResponse(data)


class AjaxFormMixin:

    def form_invalid(self, form):
        return JsonResponse(form.errors.as_data())

    def form_valid(self, form):
        self.object = form.save()
        return JsonResponse({
            'status': True,
            "pk": self.object.pk,
        })

class AddFilial(AjaxFormMixin, CreateView):
    model = Filial
    form_class = NewFilial


class ListFilial(View):

    def get(self, request):
        query = Q()
        if request.GET.get('company', None):
            query.add(Q(company=request.GET['company']), Q.AND)
        data = Filial.objects.filter(query).values(
            'id','cnpj', 'filial_name', 'active').order_by('created_at')
        return JsonResponse(list(data), safe=False)

class UpdateFilial(View):

    def post(self, request):
        id1 = request.POST.get('filial', None)
        #f = Filial.objects.get(id=id1)
        f = get_object_or_404(Filial, id=id1)
        filialname1 = request.POST.get('filial_name', None)
        active1 = request.POST.get('active', None)
        cnpj1 = request.POST.get('cnpj', None)
        f.active = active1
        f.filial_name = filialname1
        f.cnpj = cnpj1

        f.save()

        data = {
            'update': True
        }
        return JsonResponse(data)

modules/clientes/templates/clients.html
{% extends "base.html" %}

{% load static %}
{% block extra_css %}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/select2@4.0.13/dist/css/select2.min.css" integrity="sha256-FdatTf20PQr/rWg+cAKfl6j4/IY3oohFAJ7gVC3M34E=" crossorigin="anonymous">
{% endblock %}

  {% block content %}

  <div class="container">
    {% include 'includes/add-filial.html' %}
    {% include 'includes/edit-filial.html' %}
    <form action="{% url 'home:update-client' company_pk %}" method="POST">
    {% csrf_token %}
      <div class="row pt-5">
          <div class="col-3 text-secondary">
              <p class="h4"><strong>Dados Cadastrais</strong></p>
              <p class="h5">
                  Informações cadastrais da empresa cliente.
              </p>
          </div>
          <div class="col-8 offset-1 rounded shadow p-3">
              <div class="container">
                <div class="row my-3">
                    <div class="col-9">
                        <div class="form-group">
                            <label for="{{newcompany_form.active.auto_id}}" >{{form.company_name.label}}</label>
                            {{form.company_name}}
                        </div>
                    </div>
                    <div class="col-3">
                        <div class="form-group">
                            <label for="{{form.active.auto_id}}" >{{form.active.label}}</label>
                            {{form.active}}
                        </div>
                    </div>
                  </div>
              </div>
          </div>
      </div>
      <div class="row pt-5">
        <div class="col-3 text-secondary">
            <p class="h4"><strong>CNPJs</strong></p>
            <p class="h5">
                Cadastro de CNPJs relacionaos com a empresa cliente.
                Arquivos serão associados a um CNPJ durante o upload.
            </p>
        </div>
        <div class="col-8 offset-1 p-3">
            <div class="row rounded shadow ">
                <div class="col-12">
                    <div class="container">
                        <div class="row py-3 bg-light">
                            <div class="col-12 d-flex justify-content-end">
                                <button class="btn btn-primary btn-newfilial" type="button">
                                    <img class="pr-2" src="{% static 'front/images/plus.svg' %}" width="20px" height="20px"/>&nbspNovo
                                </button>
                            </div>
                        </div>
                        <div class="row" >
                            <div class="col-12" id="listFilial">
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-12 mt-4">
                                <p></p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row pt-4">
                <div class="col-6">
                    <a href="{% url 'home:delete-client' company_pk %}" class="btn btn-outline-danger btn-lg">Excluir</a>
                </div>
                <div class="col-6 d-flex justify-content-end">
                    <button class="btn btn-primary btn-lg" type="submit">Salvar</button>
                </div>
            </div>
        </div>
        </div>
    </form>
  </div>
  {% endblock content %}
  {% block extra_js %}
  <script>
    $('.btn-newfilial').click(function(e){
        e.preventDefault();
        $('#modal-newfilial').modal('show');
        $("#btn-filialedit").addClass('d-none')
        $("#btn-filialadd").removeClass('d-none')
    });

    $('.cnpj-mask').mask('00.000.000/0000-00', {reverse: true, autoUnmask: true,});
  </script>

  <script>
      $(window).on('load', function(){
            $.get("{% url 'clientes:list-filial' %}?company=" + {{company_pk}} , function(data,status) {
                $.each(data, function( index, value ) {
                    $("#listFilial").append(`
                        <div id="filial-${value.id}" class="row px-0 border-bottom pt-3">
                            <div class="col-3">
                                <p class="p-0 cnpj-mask">${value.cnpj.replace(/^(\d{2})(\d{3})(\d{3})(\d{4})(\d{2})/, "$1.$2.$3/$4-$5")}</p>
                            </div>
                            <div class="col-5">
                                <p class="p-0">${value.filial_name}</p>
                            </div>
                            <div class="col-2">
                                <div class="text-center text-light rounded-pill ${(value.active === true ? 'bg-success' : 'bg-secondary')}">
                                    ${(value.active === true ? 'Ativo' : 'Inativo')}
                                </div>
                            </div>
                            <div class="col-2 d-flex justify-content-end pb-2">
                                <button data-title='Editar CNPJ' data-id='${value.id}' data-cnpj='${value.cnpj}' data-filial='${value.filial_name}' data-active='${value.active}' type="button" class="btn btn-round-blue btn-editfilial"><img src="{% static 'front/images/edit.svg' %}" width="27px" height="27px"/>Editar</button>
                            </div>
                        </div>
                    `);
            });
            })
      });
  </script>

  <script>
      $('.btn-sendFilialForm').click(function(e) {
        e.preventDefault();
        var cnpjmask = $('#id_cnpj').val();
        $('#id_cnpj').unmask();
        var cnpj = $('#id_cnpj').val();
        var active = $('#id_active').val();
        var filial_name = $('#id_filial_name').val();
        var company = $('#id_company').val()
        $.ajax({
            url: '{% url "clientes:add-filial" %}',
            headers: {"X-CSRFToken": '{{ csrf_token }}'},
            method: 'POST',
            data: {
                'company': company,
                'cnpj': cnpj,
                'active': active,
                'filial_name': filial_name
            },
            dataType: 'json',
            success: function (data) {
                $('#modal-newfilial').modal('hide');
                $("#listFilial").append(`
                        <div id="filial" class="row border-bottom pt-3">
                            <div class="col-4">
                                <p class="p-0">${cnpjmask}</p>
                            </div>
                            <div class="col-5">
                                <p class="p-0">${filial_name}</p>
                            </div>
                            <div class="col-1">
                                <div class="text-center text-light rounded-pill ${(active === 'True' ? 'bg-success' : 'bg-secondary')}">
                                    ${(active === 'True' ? 'Ativo' : 'Inativo')}
                                </div>
                            </div>
                            <div class="col-2 d-flex justify-content-end pb-2">
                                <button data-id='${data.pk}' data-cnpj='${cnpj}' data-filial='${filial_name}' data-active='${active}' type="button" class="btn btn-round-blue btn-editfilial"><img src="{% static 'front/images/edit.svg' %}" width="24px" height="24px"/>Editar</button>
                            </div>
                        </div>
                    `);
            }
        })

      })

  </script>

    <script>
        $(document).on('click', '.btn-editfilial', function (e) {
            $('#modal-newfilial').modal('show');
            $('#addFilial').each (function(){
                this.reset();
            });
            $("#addFilial").trigger( "reset" );
            $("#btn-filialedit").removeClass('d-none')
            $("#btn-filialadd").addClass('d-none')
            $('#id_filial').val($(e.target).data('id'));
            $('#id_cnpj').val($(e.target).data('cnpj'));
            $('#id_filial_name').val($(e.target).data('filial'));
            if ($(e.target).data('active') === false) {
                $("#id_active option[value='False']").attr("selected", "selected");
            } else {
                $("#id_active option[value='True']").attr("selected", "selected");
            }
        });
    </script>

    <script>
        $('.btn-editFilialForm').click(function(e) {
            
            e.preventDefault();
            var cnpjmask = $('#id_cnpj').val();
            $('#id_cnpj').unmask();
            var filial = $('#id_filial').val();
            var cnpj = $('#id_cnpj').val();
            var active = $('#id_active').val();
            var filial_name = $('#id_filial_name').val();
            var company = $('#id_company').val()
            $.ajax({
                url: '{% url "clientes:update-filial" %}',
                headers: {"X-CSRFToken": '{{ csrf_token }}'},
                method: 'POST',
                data: {
                    'filial': filial,
                    'company': company,
                    'cnpj': cnpj,
                    'active': active,
                    'filial_name': filial_name
                },
                dataType: 'json',
                success: function (data) {
                    location.reload();
                }
            })
        })

    </script>

  {% endblock extra_js %}