ACME/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('modules.home.urls')),
    path('clientes', include('modules.clientes.urls')),
    # path('accounts/', include('users.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

modules/home/urls.py
from django.contrib import admin
from django.conf.urls import url
from django.urls import path
from django.urls.conf import include
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.Home.as_view(), name='index'),
    path('add-client', views.CreateClient.as_view(), name='add-client'),
    path('update-client/<int:pk>/', views.UpdateClient.as_view(), name='update-client'),
    path('delete/<int:pk>/', views.DeleteClient.as_view(), name='delete-client')
]

tools/general/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _


class SuperClass(models.Model):
    class Meta:
        abstract = True
        ordering = ('-created_at',)

    created_at = models.DateTimeField(_('created at'), auto_now_add=True)
    updated_at = models.DateTimeField(_('updated at'), auto_now=True)
    deleted_at = models.DateTimeField(_('deleted at'), null=True, blank=True)
    active = models.BooleanField(_('active'), default=True)

tools/general/views.py
from django.shortcuts import render

# Create your views here.

tools/templates/includes/add-filial.html
  <div class="modal" tabindex="-1" id="modal-newfilial">
    <div class="modal-dialog modal-lg">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title">Adicionar uma nova filial</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <div class="container-fluid">
          <form id="addFilial">
            {% csrf_token %}
            {{newfilial.company}}
            <input type="hidden" name="filial" value="" id="id_filial">
            <div class="row py-3">
                <div class="col-12">
                    <div class="form-group">
                        <label for="{{newcompany_form.active.auto_id}}" >{{newfilial.active.label}}</label>
                        {{newfilial.active}}
                    </div>
                </div>
            </div>
            <div class="row py-3">
              <div class="col-12">
                  <div class="form-group">
                      <label for="{{newcompany_form.company_name.auto_id}}" >{{newfilial.cnpj.label}}</label>
                      {{newfilial.cnpj}}
                  </div>
              </div>
          </div>
            <div class="row py-3">
                <div class="col-12">
                    <div class="form-group">
                        <label for="{{newcompany_form.company_name.auto_id}}" >{{newfilial.filial_name.label}}</label>
                        {{newfilial.filial_name}}
                    </div>
                </div>
            </div>
            <div class="row pt-3">
              <div class="col-6">
                <button id="bt-reset" class="btn btn-danger" type="reset">Limpar</button>
              </div>
              <div id="btn-filialadd" class="col-6 d-flex justify-content-end">
                <button  class="btn btn-primary btn-sendFilialForm" type="button">Salvar</button>
                
              </div>
              <div id="btn-filialedit" class="col-6 d-flex justify-content-end d-none">
                <button  class="btn btn-primary btn-editFilialForm" type="button">Salvar</button>                
              </div>
            </div>
          </form>
          </div>
        </div>

      </div>
    </div>
    <script>
      $(document).ready(function() {
        $('#modal-newfilial').on('click', '.close', function() {
          $('#modal-newfilial').modal('hide');
        });
      });
    </script>
  </div>

tools/templates/includes/edit-filial.html
<div class="modal" tabindex="-1" id="modal-editfilial">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Editando CNPJ</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div class="container-fluid">
        <form id="editFilial">
          {% csrf_token %}
          {{newfilial.company}}
          <div class="row py-3">
              <div class="col-12">
                  <div class="form-group editfilial">
                      <label for="{{newfilial.active.auto_id}}" >{{newfilial.active.label}}</label>
                      {{newfilial.active}}
                  </div>
              </div>
          </div>
          <div class="row py-3">
            <div class="col-12">
                <div class="form-group editfilial">
                    <label for="{{newfilial.cnpj.auto_id}}" >{{newfilial.cnpj.label}}</label>
                    {{newfilial.cnpj}}
                </div>
            </div>
        </div>
          <div class="row py-3">
              <div class="col-12">
                  <div class="form-group editfilial">
                      <label for="{{newfilial.filial_name.auto_id}}" >{{newfilial.filial_name.label}}</label>
                      {{newfilial.filial_name}}
                  </div>
              </div>
          </div>
          <div class="row pt-3">
            <div class="col-6">
              <button id="bt-reset" class="btn btn-danger" type="reset">Limpar</button>
            </div>
            <div class="col-6 d-flex justify-content-end">
              <button class="btn btn-primary" type="button">Salvar</button>
            </div>
          </div>
        </form>
        </div>
      </div>
    </div>
  </div>
  <script>
    $(document).ready(function() {
      $('#modal-editfilial').on('click', '.close', function() {
        $('#modal-editfilial').modal('hide');
      });
    });
  </script>
</div>

tools/templates/includes/navbar.html
{% load static %} 
{% load i18n %}

<nav class="navbar shadow navbar-expand-lg">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'home:index' %}"><strong>ACME</strong></a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDarkDropdown" aria-controls="navbarNavDarkDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDarkDropdown">
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'home:index' %}">Dashboard</span></a>
            </li>
            <li class="nav-item">
                {% comment %} clientes não possui funcionalidade {% endcomment %}
                <a class="nav-link" href="{% url 'home:index' %}">Clientes</span></a>
            </li>
        </ul>
        <ul class="nav navbar-nav ms-auto">
            <li class="nav-item dropdown">
                <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">Admin</a>
                <div class="dropdown-menu dropdown-menu-end">
                    <a href="{% url 'home:index' %}" class="dropdown-item"><span class="text-dark">Dashboard</span></a>
                    <a href="#" class="dropdown-item"><span class="text-dark">Clientes</span></a>
                    <div class="dropdown-divider"></div>
                    <a href="#" class="dropdown-item"><span class="text-dark">Sair</span></a>
                </div>
            </li>
        </ul>
      </div>
    </div>
</nav>

tools/templates/includes/new-company.html
  <div class="modal" tabindex="-1" id="modal-newcompany">
    <div class="modal-dialog modal-lg">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title">Adicionar um novo Cliente</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <div class="container-fluid">
          <form action="{% url 'home:add-client' %}" method="POST">
            {% csrf_token %}
            <div class="row py-3">
                <div class="col-12">
                    <div class="form-group">
                        <label for="{{form.active.auto_id}}" >{{form.active.label}}</label>
                        {{form.active}}
                    </div>
                </div>
            </div>
            <div class="row py-3">
                <div class="col-12">
                    <div class="form-group">
                        <label for="{{newcompany_form.company_name.auto_id}}" >{{form.company_name.label}}</label>
                        {{form.company_name}}
                    </div>
                </div>
            </div>
            <div class="row pt-3">
              <div class="col-6">
                <button id="bt-reset" class="btn btn-danger" type="reset">Limpar</button>
              </div>
              <div class="col-6 d-flex justify-content-end">
                <button class="btn btn-primary" type="submit">Salvar</button>
              </div>
            </div>
          </form>
          </div>
        </div>
      </div>
    </div>
    <script>
      $(document).ready(function() {
        $('#modal-newcompany').on('click', '.close', function() {
          $('#modal-newcompany').modal('hide');
        });
      });
    </script>
  </div>